// PORNHUB
export const PORNHUB_FILTER_PLAYLIST_PAGE = 'PORNHUB_FILTER_PLAYLIST_PAGE'

// YOUTUBE
export const YOUTUBE_FILTER_SEARCH_RESULTS = 'YOUTUBE_FILTER_SEARCH_RESULTS'
export const YOUTUBE_OPEN_MODAL = 'YOUTUBE_OPEN_MODAL'
